name: CI/CD Pipeline da Calculadora Simples

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9]

    steps:
      - name: Verifica o Repo
        uses: actions/checkout@v2

      - name: Setup do Poetry
        uses: python-poetry/setup-poetry@v2
        with:
          version: "1.1"

      - name: Instalando depêndencias
        run: |
          poetry install

      - name: Rodando os testes
        run: |
          pyteste .\c14\testes.py
        continue-on-error: true

      - name: Upload do resultado dos testes
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: ./test-results

  build:
    runs-on: ubuntu-latest
    needs: []  

    steps:
      - name: Verifica o Repo
        uses: actions/checkout@v2

      - name: Setup do Poetry
        uses: python-poetry/setup-poetry@v2
        with:
          version: "1.1"

      - name: Instalando depêndencias
        run: |
          poetry install

      - name: Buildando o pacote
        run: |
          poetry build

      - name: Upload dos artefatos de build
        uses: actions/upload-artifact@v2
        with:
          name: build-artifacts
          path: dist/

  notification:
    runs-on: ubuntu-latest
    needs: [tests, build]
    if: always()

    steps:
      - name: Envia a notificação por email
        run: |
          echo "Pipeline Executado!" | mail -s "Status da Pipeline" ${{ secrets.NOTIFY_EMAIL }}
        env:
          NOTIFY_EMAIL: ${{ secrets.NOTIFY_EMAIL }}
